// End-to-end test : drive the full enrolment pipeline like an
// operator would, then start a real Bridge server using the
// extracted kit. Confirms that the certs generated by
// `lmbox-bridge-enroll` are actually consumable by the Bridge
// without manual fixup.
//
// Why we exec a subprocess for the bridge-enroll CLI rather than
// importing main() : the CLI calls os.Exit(...) on each subcommand,
// which would terminate the test process. Subprocess execution
// keeps the test runner isolated and exercises the same binary
// path operators actually run.

package main_test

import (
	"crypto/tls"
	"crypto/x509"
	"encoding/json"
	"encoding/pem"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestE2E_EnrolmentToBridgeBoot(t *testing.T) {
	if testing.Short() {
		t.Skip("E2E exec test skipped under -short")
	}
	// 0. Build the enroll CLI binary into the test temp dir.
	bin := buildEnrollBinary(t)

	// 1. customer-init
	enrolDir := filepath.Join(t.TempDir(), "enrolments")
	run(t, bin, "customer-init",
		"--customer-id", "acme-industries",
		"--customer-name", "Acme Industries SAS",
		"--output", enrolDir,
		"--ca-lifetime", "1y",
	)
	custDir := filepath.Join(enrolDir, "acme-industries")
	assertExists(t, filepath.Join(custDir, "root", "root-ca.crt"))
	assertExists(t, filepath.Join(custDir, "root", "root-ca.key"))
	assertExists(t, filepath.Join(custDir, "bridge", "box-ca.pem"))
	assertExists(t, filepath.Join(custDir, "crl", "box-revocations.crl"))
	assertExists(t, filepath.Join(custDir, "config.yaml"))
	assertExists(t, filepath.Join(custDir, "enrolment.json"))

	// 2. mint-bridge-server with localhost SANs.
	run(t, bin, "mint-bridge-server",
		"--customer-id", "acme-industries",
		"--output", enrolDir,
		"--cn", "lmbox-bridge",
		"--dns", "localhost",
		"--ip", "127.0.0.1",
	)
	assertExists(t, filepath.Join(custDir, "bridge", "bridge-server.crt"))
	assertExists(t, filepath.Join(custDir, "bridge", "bridge-server.key"))

	// 3. mint-bridge-outbound needs a "cloud CA" — create one
	//    self-signed via the root CA we just generated. In real
	//    production this is an LMbox-controlled CA; here we
	//    repurpose the customer root for simplicity.
	cloudCert := filepath.Join(custDir, "root", "root-ca.crt")
	cloudKey := filepath.Join(custDir, "root", "root-ca.key")
	run(t, bin, "mint-bridge-outbound",
		"--customer-id", "acme-industries",
		"--output", enrolDir,
		"--cloud-ca-cert", cloudCert,
		"--cloud-ca-key", cloudKey,
	)
	assertExists(t, filepath.Join(custDir, "bridge", "bridge-out.crt"))

	// 4. mint-box-cert.
	run(t, bin, "mint-box-cert",
		"--customer-id", "acme-industries",
		"--output", enrolDir,
		"--serial", "BOX-ACME-001",
	)
	assertExists(t, filepath.Join(custDir, "boxes", "BOX-ACME-001.crt"))

	// 5. pack-kit + verify-kit roundtrip.
	hmacKeyPath := filepath.Join(t.TempDir(), "hmac.key")
	if err := os.WriteFile(hmacKeyPath,
		[]byte("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef\n"),
		0o600); err != nil {
		t.Fatal(err)
	}
	kitOut := filepath.Join(t.TempDir(), "acme-bridge-kit.tar.gz")
	run(t, bin, "pack-kit",
		"--customer-id", "acme-industries",
		"--source", enrolDir,
		"--hmac-key", hmacKeyPath,
		"--output", kitOut,
	)
	assertExists(t, kitOut)
	assertExists(t, kitOut+".hmac")

	// 6. Extract the kit into a fresh dir, simulating the RSSI
	//    receiving and unpacking it.
	rssiDir := filepath.Join(t.TempDir(), "rssi-deploy")
	run(t, bin, "verify-kit",
		"--kit", kitOut,
		"--hmac-key", hmacKeyPath,
		"--extract", rssiDir,
	)
	assertExists(t, filepath.Join(rssiDir, "certs/bridge-server.crt"))
	assertExists(t, filepath.Join(rssiDir, "certs/box-ca.pem"))
	assertExists(t, filepath.Join(rssiDir, "config.yaml"))

	// 7. Verify the extracted certs form a valid chain : a box
	//    client cert signed by the customer root must verify
	//    against box-ca.pem.
	boxCAPem, _ := os.ReadFile(filepath.Join(rssiDir, "certs/box-ca.pem"))
	boxCABlock, _ := pem.Decode(boxCAPem)
	if boxCABlock == nil {
		t.Fatal("box-ca.pem is not a PEM block")
	}
	boxCA, err := x509.ParseCertificate(boxCABlock.Bytes)
	if err != nil {
		t.Fatalf("parse box-ca: %v", err)
	}
	boxCertPem, _ := os.ReadFile(filepath.Join(custDir, "boxes", "BOX-ACME-001.crt"))
	boxCertBlock, _ := pem.Decode(boxCertPem)
	boxCert, err := x509.ParseCertificate(boxCertBlock.Bytes)
	if err != nil {
		t.Fatalf("parse box cert: %v", err)
	}
	pool := x509.NewCertPool()
	pool.AddCert(boxCA)
	if _, err := boxCert.Verify(x509.VerifyOptions{
		Roots:     pool,
		KeyUsages: []x509.ExtKeyUsage{x509.ExtKeyUsageClientAuth},
	}); err != nil {
		t.Fatalf("box cert does not verify against box-ca.pem: %v", err)
	}

	// 8. Bring up an httptest TLS server using the bridge-server
	//    cert + key from the kit. Confirms the Bridge would
	//    actually load those files into tls.LoadX509KeyPair.
	srvCert, err := tls.LoadX509KeyPair(
		filepath.Join(rssiDir, "certs/bridge-server.crt"),
		filepath.Join(rssiDir, "certs/bridge-server.key"),
	)
	if err != nil {
		t.Fatalf("tls.LoadX509KeyPair on extracted certs: %v", err)
	}
	tlsCfg := &tls.Config{
		Certificates: []tls.Certificate{srvCert},
		ClientCAs:    pool,
		ClientAuth:   tls.RequireAndVerifyClientCert,
		MinVersion:   tls.VersionTLS12,
	}
	hs := httptest.NewUnstartedServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(204)
	}))
	hs.TLS = tlsCfg
	hs.StartTLS()
	defer hs.Close()

	// 9. Make a request as the box cert.
	boxKeyPem, _ := os.ReadFile(filepath.Join(custDir, "boxes", "BOX-ACME-001.key"))
	boxKeyBlock, _ := pem.Decode(boxKeyPem)
	boxKey, _ := x509.ParseECPrivateKey(boxKeyBlock.Bytes)
	clientCert := tls.Certificate{
		Certificate: [][]byte{boxCertBlock.Bytes},
		PrivateKey:  boxKey,
	}
	client := &http.Client{
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{
				RootCAs:      pool,
				Certificates: []tls.Certificate{clientCert},
				MinVersion:   tls.VersionTLS12,
			},
		},
	}
	resp, err := client.Get(hs.URL + "/api/heartbeats/BOX-ACME-001")
	if err != nil {
		t.Fatalf("box request: %v", err)
	}
	resp.Body.Close()
	if resp.StatusCode != 204 {
		t.Fatalf("status=%d, want 204", resp.StatusCode)
	}

	// 10. enrolment.json metadata reflects every minted cert.
	metaBytes, _ := os.ReadFile(filepath.Join(custDir, "enrolment.json"))
	if !strings.Contains(string(metaBytes), `"customer_id": "acme-industries"`) {
		t.Fatalf("metadata missing customer_id: %s", metaBytes)
	}
	if !strings.Contains(string(metaBytes), "BridgeServer") &&
		!strings.Contains(string(metaBytes), "bridge_server") {
		t.Fatalf("metadata missing bridge_server entry: %s", metaBytes)
	}
	var parsed map[string]any
	if err := json.Unmarshal(metaBytes, &parsed); err != nil {
		t.Fatalf("metadata not valid JSON: %v", err)
	}
	if g, ok := parsed["audit_genesis"].(string); !ok || g == "" {
		t.Fatal("audit_genesis missing or empty in metadata")
	}
}

// ─── helpers ─────────────────────────────────────────────────────

func buildEnrollBinary(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	bin := filepath.Join(dir, "lmbox-bridge-enroll")
	cmd := exec.Command("go", "build", "-o", bin, "github.com/rlacotte/lmbox-bridge/cmd/lmbox-bridge-enroll")
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("build enroll binary: %v\n%s", err, out)
	}
	return bin
}

func run(t *testing.T, bin string, args ...string) string {
	t.Helper()
	cmd := exec.Command(bin, args...)
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("%s %s: %v\n%s", filepath.Base(bin),
			strings.Join(args, " "), err, out)
	}
	return string(out)
}

func assertExists(t *testing.T, path string) {
	t.Helper()
	if _, err := os.Stat(path); err != nil {
		t.Fatalf("missing %s: %v", path, err)
	}
}

// silence unused
var _ = io.EOF
var _ = fmt.Sprintf
